Repository Quadrition/UKS-client, pull requests merged in 2022-02, with the labels that each got.

#7 component setup
  client/package-lock.json
  client/package.json
  client/src/app/app.module.ts
  client/src/app/components/issue/all-issues/all-issues.component.html
  client/src/app/components/issue/all-issues/all-issues.component.scss
  client/src/app/components/issue/all-issues/all-issues.component.spec.ts
  client/src/app/components/issue/all-issues/all-issues.component.ts
  client/src/app/components/issue/edit-issue/edit-issue.component.html
  client/src/app/components/issue/edit-issue/edit-issue.component.scss
  client/src/app/components/issue/edit-issue/edit-issue.component.spec.ts
  client/src/app/components/issue/edit-issue/edit-issue.component.ts
  client/src/app/components/issue/issue.module.ts
  client/src/app/components/material-module.ts
  client/src/app/components/navbar/navbar-user/navbar-user.component.html
  client/src/app/components/project/all-projects/all-projects.component.html
  client/src/app/components/project/all-projects/all-projects.component.scss
  client/src/app/components/project/all-projects/all-projects.component.spec.ts
  client/src/app/components/project/all-projects/all-projects.component.ts
  client/src/app/components/project/edit-project/edit-project.component.html
  client/src/app/components/project/edit-project/edit-project.component.scss
  client/src/app/components/project/edit-project/edit-project.component.spec.ts
  client/src/app/components/project/edit-project/edit-project.component.ts
  client/src/app/components/project/project.module.ts
Labels: configure

#15 added registration page
  client/src/app/app-routing/routes.ts
  client/src/app/components/auth/auth.module.ts
  client/src/app/components/auth/registration/registration.component.html
  client/src/app/components/auth/registration/registration.component.scss
  client/src/app/components/auth/registration/registration.component.spec.ts
  client/src/app/components/auth/registration/registration.component.ts
  client/src/app/services/authentication/authentication.service.ts
Labels: enhancement

#16 fe: stateChange view, edit, delete and create
  client/src/app/app-routing/routes.ts
  client/src/app/app.module.ts
  client/src/app/components/label/all-labels/all-labels.component.html
  client/src/app/components/navbar/navbar-user/navbar-user.component.html
  client/src/app/components/stateChange/all-state-changes/all-state-changes.component.html
  client/src/app/components/stateChange/all-state-changes/all-state-changes.component.scss
  client/src/app/components/stateChange/all-state-changes/all-state-changes.component.spec.ts
  client/src/app/components/stateChange/all-state-changes/all-state-changes.component.ts
  client/src/app/components/stateChange/edit-state-change/edit-state-change.component.html
  client/src/app/components/stateChange/edit-state-change/edit-state-change.component.scss
  client/src/app/components/stateChange/edit-state-change/edit-state-change.component.spec.ts
  client/src/app/components/stateChange/edit-state-change/edit-state-change.component.ts
  client/src/app/components/stateChange/new-state-change/new-state-change.component.html
  client/src/app/components/stateChange/new-state-change/new-state-change.component.scss
  client/src/app/components/stateChange/new-state-change/new-state-change.component.spec.ts
  client/src/app/components/stateChange/new-state-change/new-state-change.component.ts
  client/src/app/components/stateChange/stateChange.module.ts
  client/src/app/model/StateChange.ts
  client/src/app/services/stateChange/stateChange.service.spec.ts
  client/src/app/services/stateChange/stateChange.service.ts
  client/src/environments/environment.ts
Labels: enhancement

#18 Feature git repo component
  client/package-lock.json
  client/src/app/app-routing/routes.ts
  client/src/app/app.module.ts
  client/src/app/components/gitRepo/all-git-repos/all-git-repos.component.html
  client/src/app/components/gitRepo/all-git-repos/all-git-repos.component.scss
  client/src/app/components/gitRepo/all-git-repos/all-git-repos.component.spec.ts
  client/src/app/components/gitRepo/all-git-repos/all-git-repos.component.ts
  client/src/app/components/gitRepo/edit-git-repo/edit-git-repo.component.html
  client/src/app/components/gitRepo/edit-git-repo/edit-git-repo.component.scss
  client/src/app/components/gitRepo/edit-git-repo/edit-git-repo.component.spec.ts
  client/src/app/components/gitRepo/edit-git-repo/edit-git-repo.component.ts
  client/src/app/components/gitRepo/git-repo.module.ts
  client/src/app/components/gitRepo/new-git-repo/new-git-repo.component.html
  client/src/app/components/gitRepo/new-git-repo/new-git-repo.component.scss
  client/src/app/components/gitRepo/new-git-repo/new-git-repo.component.spec.ts
  client/src/app/components/gitRepo/new-git-repo/new-git-repo.component.ts
  client/src/app/services/New Text Document.txt
  client/src/app/services/git-repo/git-repo.service.spec.ts
  client/src/app/services/git-repo/git-repo.service.ts
  client/src/environments/environment.ts
  client/src/index.html
Labels: enhancement

#20 Feature label application event comment components
  client/src/app/app-routing/routes.ts
  client/src/app/app.module.ts
  client/src/app/components/comment/all-comments/all-comments.component.html
  client/src/app/components/comment/all-comments/all-comments.component.scss
  client/src/app/components/comment/all-comments/all-comments.component.spec.ts
  client/src/app/components/comment/all-comments/all-comments.component.ts
  client/src/app/components/comment/comment.module.ts
  client/src/app/components/comment/edit-comment/edit-comment.component.html
  client/src/app/components/comment/edit-comment/edit-comment.component.scss
  client/src/app/components/comment/edit-comment/edit-comment.component.spec.ts
  client/src/app/components/comment/edit-comment/edit-comment.component.ts
  client/src/app/components/comment/new-comment/new-comment.component.html
  client/src/app/components/comment/new-comment/new-comment.component.scss
  client/src/app/components/comment/new-comment/new-comment.component.spec.ts
  client/src/app/components/comment/new-comment/new-comment.component.ts
  client/src/app/components/event/all-events/all-events.component.html
  client/src/app/components/event/all-events/all-events.component.scss
  client/src/app/components/event/all-events/all-events.component.spec.ts
  client/src/app/components/event/all-events/all-events.component.ts
  client/src/app/components/event/edit-event/edit-event.component.html
  client/src/app/components/event/edit-event/edit-event.component.scss
  client/src/app/components/event/edit-event/edit-event.component.spec.ts
  client/src/app/components/event/edit-event/edit-event.component.ts
  client/src/app/components/event/event.module.ts
  client/src/app/components/event/new-event/new-event.component.html
  client/src/app/components/event/new-event/new-event.component.scss
  client/src/app/components/event/new-event/new-event.component.spec.ts
  client/src/app/components/event/new-event/new-event.component.ts
  client/src/app/components/label/edit-label/edit-label.component.ts
  client/src/app/components/label/new-label/new-label.component.ts
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.html
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.scss
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.spec.ts
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.ts
  client/src/app/components/labelApplication/edit-labelApplication/edit-labelApplication.component.html
  client/src/app/components/labelApplication/edit-labelApplication/edit-labelApplication.component.scss
  client/src/app/components/labelApplication/edit-labelApplication/edit-labelApplication.component.spec.ts
  client/src/app/components/labelApplication/edit-labelApplication/edit-labelApplication.component.ts
  client/src/app/components/labelApplication/labelApplication.module.ts
  client/src/app/components/labelApplication/new-labelApplication/new-labelApplication.component.html
  client/src/app/components/labelApplication/new-labelApplication/new-labelApplication.component.scss
  client/src/app/components/labelApplication/new-labelApplication/new-labelApplication.component.spec.ts
  client/src/app/components/labelApplication/new-labelApplication/new-labelApplication.component.ts
  client/src/app/components/navbar/navbar-user/navbar-user.component.html
  client/src/app/model/Comment.ts
  client/src/app/model/Event.ts
  client/src/app/model/LabelApplication.ts
  client/src/app/services/comment/comment.service.spec.ts
  client/src/app/services/comment/comment.service.ts
  client/src/app/services/event/event.service.spec.ts
  client/src/app/services/event/event.service.ts
  client/src/app/services/label-application/label-application.service.ts
  client/src/app/services/labelApplication/labelApplication.service.spec.ts
  client/src/app/services/labelApplication/labelApplication.service.ts
  client/src/environments/environment.ts
Labels: enhancement

#24 Feature task component
  client/src/app/app-routing/routes.ts
  client/src/app/app.module.ts
  client/src/app/components/navbar/navbar-user/navbar-user.component.html
  client/src/app/components/stateChange/new-state-change/new-state-change.component.ts
  client/src/app/components/task/all-tasks/all-tasks.component.html
  client/src/app/components/task/all-tasks/all-tasks.component.scss
  client/src/app/components/task/all-tasks/all-tasks.component.spec.ts
  client/src/app/components/task/all-tasks/all-tasks.component.ts
  client/src/app/components/task/edit-task/edit-task.component.html
  client/src/app/components/task/edit-task/edit-task.component.scss
  client/src/app/components/task/edit-task/edit-task.component.spec.ts
  client/src/app/components/task/edit-task/edit-task.component.ts
  client/src/app/components/task/new-task/new-task.component.html
  client/src/app/components/task/new-task/new-task.component.scss
  client/src/app/components/task/new-task/new-task.component.spec.ts
  client/src/app/components/task/new-task/new-task.component.ts
  client/src/app/components/task/task.module.ts
  client/src/app/services/task/task.service.spec.ts
  client/src/app/services/task/task.service.ts
  client/src/environments/environment.ts
Labels: documentation

#25 fe: task creation done
  client/src/app/components/task/all-tasks/all-tasks.component.html
  client/src/app/components/task/edit-task/edit-task.component.html
  client/src/app/components/task/edit-task/edit-task.component.scss
  client/src/app/components/task/edit-task/edit-task.component.ts
Labels: enhancement

#26 Feature label application event comment components
  client/src/app/components/comment/all-comments/all-comments.component.html
  client/src/app/components/event/all-events/all-events.component.html
  client/src/app/components/event/all-events/all-events.component.ts
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.html
  client/src/app/components/navbar/navbar-user/navbar-user.component.html
Labels: enhancement

#27 adding milestone and label into project
  client/src/app/app-routing/routes.ts
  client/src/app/components/label/all-labels/all-labels.component.html
  client/src/app/components/label/edit-label/edit-label.component.ts
  client/src/app/components/label/new-label/new-label.component.ts
  client/src/app/components/milestone/all-milestones/all-milestones.component.html
  client/src/app/components/milestone/new-milestone/new-milestone.component.ts
  client/src/app/components/project/all-projects/all-projects.component.ts
  client/src/app/components/project/project-details/project-details.component.ts
  client/src/app/services/milestone/milestone.service.ts
  client/src/app/services/project/project.service.ts
Labels: enhancement

#28 Feature task component
  client/src/app/components/task/all-tasks/all-tasks.component.html
  client/src/app/components/task/all-tasks/all-tasks.component.ts
  client/src/app/components/task/edit-task/edit-task.component.ts
  client/src/app/components/task/new-task/new-task.component.html
  client/src/app/components/task/new-task/new-task.component.scss
  client/src/app/components/task/new-task/new-task.component.ts
Labels: enhancement

#30 Feature label application and comment components
  client/src/app/components/comment/new-comment/new-comment.component.html
  client/src/app/components/comment/new-comment/new-comment.component.ts
  client/src/app/components/labelApplication/new-labelApplication/new-labelApplication.component.html
  client/src/app/components/labelApplication/new-labelApplication/new-labelApplication.component.ts
Labels: enhancement

#31 Feature label application event comment components
  client/src/app/components/comment/all-comments/all-comments.component.html
  client/src/app/components/comment/all-comments/all-comments.component.ts
  client/src/app/components/comment/edit-comment/edit-comment.component.html
  client/src/app/components/comment/edit-comment/edit-comment.component.ts
  client/src/app/components/event/all-events/all-events.component.html
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.html
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.ts
  client/src/app/components/labelApplication/edit-labelApplication/edit-labelApplication.component.html
  client/src/app/components/labelApplication/edit-labelApplication/edit-labelApplication.component.ts
Labels: enhancement

#35 adding gitrepo into project
  client/src/app/app-routing/routes.ts
  client/src/app/components/project/all-projects/all-projects.component.ts
  client/src/app/components/project/new-project/new-project.component.ts
Labels: enhancement

#34 modified navbar
  client/src/app/components/navbar/navbar-user/navbar-user.component.html
Labels: enhancement

#37 Feature label application event comment components
  client/src/app/components/comment/all-comments/all-comments.component.html
  client/src/app/components/comment/all-comments/all-comments.component.ts
  client/src/app/components/event/all-events/all-events.component.html
  client/src/app/components/event/all-events/all-events.component.ts
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.html
  client/src/app/components/labelApplication/all-labelApplications/all-labelApplications.component.ts
  client/src/app/services/comment/comment.service.ts
  client/src/app/services/event/event.service.ts
  client/src/app/services/labelApplication/labelApplication.service.ts
Labels: enhancement

#38 profile details, update profile
  client/src/app/app-routing/routes.ts
  client/src/app/components/user/profile-details/profile-details.component.html
  client/src/app/components/user/profile-details/profile-details.component.scss
  client/src/app/components/user/profile-details/profile-details.component.spec.ts
  client/src/app/components/user/profile-details/profile-details.component.ts
  client/src/app/components/user/user.module.ts
  client/src/app/services/user/user.service.ts
Labels: enhancement

#39 history view for milestone
  client/src/app/components/milestone/edit-milestone/edit-milestone.component.html
  client/src/app/components/milestone/edit-milestone/edit-milestone.component.ts
  client/src/app/model/History.ts
  client/src/app/services/history/history.service.spec.ts
  client/src/app/services/history/history.service.ts
  client/src/environments/environment.ts
Labels: enhancement

#41 Feature history
  client/src/app/components/comment/edit-comment/edit-comment.component.html
  client/src/app/components/comment/edit-comment/edit-comment.component.ts
  client/src/app/components/label/edit-label/edit-label.component.html
  client/src/app/components/label/edit-label/edit-label.component.ts
Labels: enhancement

#42 history view updated
  client/src/app/components/auth/login-page/login-page.component.ts
  client/src/app/components/comment/all-comments/all-comments.component.html
  client/src/app/components/comment/all-comments/all-comments.component.ts
  client/src/app/components/comment/edit-comment/edit-comment.component.html
  client/src/app/components/comment/edit-comment/edit-comment.component.ts
  client/src/app/components/navbar/navbar-user/navbar-user.component.html
  client/src/app/components/user/profile-details/profile-details.component.html
  client/src/app/components/user/profile-details/profile-details.component.ts
Labels: enhancement

#43 Added brand crud calls
  client/src/app/components/branch/branches-list/branches-list.component.ts
  client/src/app/services/branch/branch.service.spec.ts
  client/src/app/services/branch/branch.service.ts
  client/src/environments/environment.ts
Labels: enhancement

#44 Added branches CRUD
  client/src/app/app-routing/routes.ts
  client/src/app/components/branch/branch.module.ts
  client/src/app/components/branch/branches-list/branches-list.component.html
  client/src/app/components/branch/branches-list/branches-list.component.scss
  client/src/app/components/branch/branches-list/branches-list.component.spec.ts
  client/src/app/components/branch/branches-list/branches-list.component.ts
  client/src/app/components/branch/edit-branch-dialog/edit-branch-dialog.component.html
  client/src/app/components/branch/edit-branch-dialog/edit-branch-dialog.component.scss
  client/src/app/components/branch/edit-branch-dialog/edit-branch-dialog.component.spec.ts
  client/src/app/components/branch/edit-branch-dialog/edit-branch-dialog.component.ts
  client/src/app/components/branch/new-branch-dialog/new-branch-dialog.component.html
  client/src/app/components/branch/new-branch-dialog/new-branch-dialog.component.scss
  client/src/app/components/branch/new-branch-dialog/new-branch-dialog.component.spec.ts
  client/src/app/components/branch/new-branch-dialog/new-branch-dialog.component.ts
  client/src/app/components/gitRepo/git-repo.module.ts
  client/src/app/components/gitRepo/repo/repo.component.html
  client/src/app/components/gitRepo/repo/repo.component.scss
  client/src/app/components/gitRepo/repo/repo.component.spec.ts
  client/src/app/components/gitRepo/repo/repo.component.ts
  client/src/app/services/branch/branch.service.spec.ts
  client/src/app/services/branch/branch.service.ts
  client/src/environments/environment.ts
Labels: enhancement
